name: arcore_flutter_plugin_example
description: ARCore SDK for Android
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  splashscreen: ^1.3.5
  provider: ^5.0.0
  url_launcher: ^6.0.9

  firebase_storage: ^10.0.3
  firebase_core: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash:  ^0.2.8

  flutter_launcher_icons:  ^0.8.1

  arcore_flutter_plugin:
    path: ../

flutter_native_splash:
  color: "#333333"
  image: assets/images/logoVertical.png
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/logoSimple2.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/comidaItaliana.webp
  - assets/images/comidaItaliana.webp
  - assets/images/comidaColombiana.webp
  - assets/images/comidaPostre.webp
  - assets/images/comidaRapida.webp
  - assets/images/comidaSaludable.webp
  - assets/images/comidaVinos.webp
  - assets/images/aboutUs.webp
  - assets/images/flecha.gif
  - assets/images/mano.gif
  - assets/images/products/pasta.webp
  - assets/images/products/pizza.webp
  - assets/images/products/paisa.webp
  - assets/images/products/productoNuevo.webp
  - assets/images/products/papas.webp
  - assets/images/products/wopper.webp
  - assets/images/products/frutas.webp
  - assets/images/products/cereza.webp
  - assets/images/products/submarino.webp
  - assets/images/products/carne.webp
  - assets/images/products/vinos.webp
  - assets/images/products/quesos.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages